# config.yaml 文件应该与 aat_dpi 可执行文件在同一路径下
# excel
excel_path: /home/ericsson/date_dpi.xlsx
output_path: /home/ericsson/date_dpi_output.xlsx
# aat gui
aat_domain: https://188.4.62.189:33341
user_name: sysadm
password: ChangeMe11
# execute config
epg_name: FOSSAEGW704BER
hosts_path: /etc/hosts
script_path: /home/ericsson/add_rule_to_etc_hosts.py
# case name
l3: aat_dpi_l3
l7: aat_dpi_l7
l3_l7: aat_dpi_l3_l7
# 对于输入 excel 中同一业务编码，但类型（3层，7层，组合）不同的数据的选取数量
date_select_max_num: 10
# {'epg_name': "apn_name"}
epg_with_apn:
    GZSAEGW2001BEr: gzcmnet2001.gd
    FOSSAEGW704BER: fscmnet704.gd