# The config.yaml file should be in the same path as the aat_dpi executable
# some file path
script_path: ./add_rule_to_etc_hosts.py         # Script file path of modify domain name and IP address relationship
# execute select
date_select_max_num: 5                          # The maximum number of different data types selected for the same service code
epg_name: FOSSAEGW704BEr                        # Select that EPG and APN as the test, epg should in below epg_with_apn
# aat gui info
aat_domain: https://188.4.62.189:33351          # The url of aat gui
user_name: sysadm                               # Aat gui login user name
password: ChangeMe11                            # Aat gui login user password
# aat case name info
l3: aat_dpi_l3                                  # Case name to test the 'Add Three Layers of Rules' data
l7: aat_dpi_l7                                  # Case name to test the 'Add Seven Layers of Rules' data
l3_l7: aat_dpi_l3_l7                            # Case name to test the 'New Combination Rule' data
# epg and apn info
# {'epg_name': "apn_name"}
epg_with_apn:
    GZSAEGW2001BEr: gzcmnet2001.gd
    FOSSAEGW704BEr: fscmnet704.gd